### ISSUE TITLE
Bot: Twitter api tokens not working

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1032]
```
Getting webhooks…
AuthenticationError: Forbidden. (HTTP status: 403, Twitter code: 200)
    at tryError (/mnt/c/Users/avaer/Documents/GitHub/ethereum-bot/node_modules/twitter-autohook/errors/index.js:53:12)
    at Autohook.getWebhooks (/mnt/c/Users/avaer/Documents/GitHub/ethereum-bot/node_modules/twitter-autohook/index.js:242:19)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Autohook.removeWebhooks (/mnt/c/Users/avaer/Documents/GitHub/ethereum-bot/node_modules/twitter-autohook/index.js:261:22)
    at async exports.createTwitterClient (/mnt/c/Users/avaer/Documents/GitHub/ethereum-bot/twitterBot.js:1681:3)
    at async /mnt/c/Users/avaer/Documents/GitHub/ethereum-bot/index.js:195:3 {
  code: 200
}
```

**Comment by avaer** [comment]
This was originally contributed by @shawticus.
