### ISSUE TITLE
GPT-J-6B endpoint

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1355]
I'm kicking off a `TRC` sub to see how far we can get with a custom GPT-J endpoint.

https://github.com/kingoflolz/mesh-transformer-jax

![image](https://user-images.githubusercontent.com/6926057/125048513-0469d080-e06e-11eb-8841-3bfaec076fa8.png)

**Comment by avaer** [comment]
I managed to set up the model and get a TPU VM `v2-8` up and running, but it OOMs, so I think the size was just not large enough to handle the model. With the above we should be able to see the required size.

```

avaer@t1v-n-490548e3-w-0:~/mesh-transformer-jax$ echo 'who is the best pony?' | python3 ./device_sample.py --config ./configs/6B_roto_256.json
jax devices: 8
jax runtime initialized in 16.7596s
using checkpoint 383500
/usr/local/lib/python3.8/dist-packages/jax/experimental/maps.py:418: UserWarning: xmap is an experimental feature and probably has bugs!
  warn("xmap is an experimental feature and probably has bugs!")
/usr/local/lib/python3.8/dist-packages/jax/lib/xla_bridge.py:316: UserWarning: jax.host_count has been renamed to jax.process_count. This alias will eventually be removed; please update your code.
  warnings.warn(
key shape (8, 2)
in shape (1, 2048)
dp 1
mp 8
2021-07-09 08:27:36.434321: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:1981] Execution of replica 3 failed: Resource exhausted: Failed to allocate request for 32.00MiB (33554432B) on device ordinal 3
2021-07-09 08:27:36.434391: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:1981] Execution of replica 4 failed: Resource exhausted: Failed to allocate request for 32.00MiB (33554432B) on device ordinal 4
2021-07-09 08:27:36.434426: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:1981] Execution of replica 5 failed: Resource exhausted: Failed to allocate request for 32.00MiB (33554432B) on device ordinal 5
2021-07-09 08:27:36.434456: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:1981] Execution of replica 2 failed: Resource exhausted: Failed to allocate request for 32.00MiB (33554432B) on device ordinal 2
2021-07-09 08:27:36.434510: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:1981] Execution of replica 7 failed: Resource exhausted: Failed to allocate request for 32.00MiB (33554432B) on device ordinal 7
2021-07-09 08:27:36.434576: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:1981] Execution of replica 1 failed: Resource exhausted: Failed to allocate request for 32.00MiB (33554432B) on device ordinal 1
2021-07-09 08:27:36.434612: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:1981] Execution of replica 6 failed: Resource exhausted: Failed to allocate request for 32.00MiB (33554432B) on device ordinal 6
2021-07-09 08:27:36.434823: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:1981] Execution of replica 0 failed: Resource exhausted: Failed to allocate request for 32.00MiB (33554432B) on device ordinal 0
Traceback (most recent call last):
  File "./device_sample.py", line 74, in <module>
    network = CausalTransformer(params)
  File "/home/avaer/mesh-transformer-jax/mesh_transformer/transformer_shard.py", line 263, in __init__
    self.state = self.init_xmap(jnp.array(key.take(mp_per_host)), x)
  File "/usr/local/lib/python3.8/dist-packages/jax/experimental/maps.py", line 524, in fun_mapped
    out_flat = xmap_p.bind(
  File "/usr/local/lib/python3.8/dist-packages/jax/experimental/maps.py", line 713, in bind
    return core.call_bind(self, fun, *args, **params)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1556, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/experimental/maps.py", line 716, in process
    return trace.process_xmap(self, fun, tracers, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 609, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/experimental/maps.py", line 559, in xmap_impl
    return xmap_callable(*args)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/pxla.py", line 1141, in execute_replicated
    out_bufs = compiled.execute_sharded_on_local_devices(input_bufs)
RuntimeError: Resource exhausted: Failed to allocate request for 32.00MiB (33554432B) on device ordinal 0: while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well).
```

**Comment by avaer** [comment]
I got it running on a TPU v2-8, the problem was probably packing too much of the model (something to do with optimizer params).

**Comment by avaer** [comment]
Script used for running is here: https://github.com/webaverse/mesh-transformer-jax/blob/hack/server.py

**Comment by avaer** [comment]
This could easily be hooked up to the bot.

**Comment by cirecrux** [comment]
Just going to leave this comment here for anyone with the same problem: 

`RuntimeError: Resource exhausted: Failed to allocate request for 32.00MiB (33554432B) on device ordinal 0: while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well).`

Assuming that you're following the fine-tune-guide from mesh-transformer-jax like I am, the problem is that the TPU has to be set up as v3-8 and not v2-8.

I wasted a whole day trying to figure out what I got wrong since I only know enough about code to copy paste error messages into the search bar. The author of the issue (avaer) is a genius for getting it to work somehow on a v2-8. Anyways, good luck out there.

**Comment by avaer** [comment]
Thanks, is `v3-8` still ultra super rare to snag?

**Comment by cirecrux** [comment]
nah, I just followed the guide wrong

**Comment by lalalune** [comment]
https://huggingface.co/bigscience/T0pp

https://huggingface.co/EleutherAI/gpt-j-6B

```
async function query(data) {
	const response = await fetch(
		"https://api-inference.huggingface.co/models/EleutherAI/gpt-j-6B",
		{
			headers: { Authorization: "Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" },
			method: "POST",
			body: JSON.stringify(data),
		}
	);
	const result = await response.json();
	return result;
}

query({"inputs": "Can you please let us know more details about your "}).then((response) => {
	console.log(JSON.stringify(response));
});
```
