### ISSUE TITLE
Totum: relative imports incorrect from GHP

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1969]
```
10:27:08 PM [vite] Internal server error: Failed to resolve import "./shaders/SilkShader" from "https:/webaverse.github.io/silk-fountains/silk-fountain-01/index.js". Does the file exist?
  Plugin: vite:import-analysis
  File: https://webaverse.github.io/silk-fountains/silk-fountain-01/index.js
  2  |
  3  |  import { DRACOLoader } from 'three/examples/jsm/loaders/DRACOLoader';
  4  |  import SilkShader from './shaders/SilkShader';
     |                          ^
  5  |  import metaversefile from 'metaversefile'; //const { useFrame, useLocalPlayer, useCleanup, /*useUi,*/ usePhysics} = metaversefile;
  6  |
      at formatError (/home/a/app/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42189:46)
      at TransformContext.error (/home/a/app/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42185:19)
      at normalizeUrl (/home/a/app/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:67284:26)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async TransformContext.transform (/home/a/app/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:67424:57)
      at async Object.transform (/home/a/app/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42396:30)
      at async doTransform (/home/a/app/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:56801:29)
10:27:08 PM [vite] new dependencies found: three/examples/jsm/loaders/DRACOLoader, updating...
[BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.
```

![](https://cdn.discordapp.com/attachments/906538392748195860/919067895307337758/unknown.png)

**Comment by avaer** [comment]
To reproduce, add this app to a scn file:

```
{
      "position": [
        0,
        0,
        0
      ],
      "start_url": "https://webaverse.github.io/silk-fountains/silk-fountain-01/index.js"
    },
```

The relative import is not resolved correctly.

**Comment by avaer** [comment]
Never mind, I think it was simply the wrong file referenced.

https://webaverse.github.io/silk-fountains/silk-fountain-01/shaders/SilkShader
https://webaverse.github.io/silk-fountains/silk-fountain-01/shaders/SilkShader.js
