### ISSUE TITLE
`node ./animations-baker.mjs` broken after upgrade to threejs r136.

### ISSUE THREAD

**Issue by gonnavis** [webaverse/app#2253]
`node ./animations-baker.mjs` broken after upgrade from r133 to threejs r134/r136: https://github.com/webaverse/three.js/pull/3, https://github.com/webaverse/three/pull/1 .

```
a@DESKTOP-CA2QMKQ:~/app$ node ./animations-baker.mjs
file:///home/a/app/packages/three/examples/jsm/curves/NURBSUtils.js:2
        Vector3,
        ^^^^^^^
SyntaxError: Named export 'Vector3' not found. The requested module '../../../build/three.module.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '../../../build/three.module.js';

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

I found there are two reasons:

1. Start from r134, we used vedorized threejs lib, and changed the dependencies style from remote npm `"three": "^0.133.1"` to local package files `"three": "./packages/three"`.
I tried with dependencies style `"three": "./packages/three"` with r133 local files still broken, so the style change is the first reason.
1. Start from r134, threejs used [`new Request`](https://github.com/mrdoob/three.js/pull/22510) which only supported in broswer, not nodejs, so even we solved the first reason, we still can't run `./animations-baker.mjs` with r134/r136.

```
C:\WWW\lib\webaverse_app_github_gonnavis>node ./animations-baker.mjs
bake error ReferenceError: Request is not defined
    at FileLoader.load (C:\WWW\lib\webaverse_app_github_gonnavis_r134\node_modules\three\build\three.js:28378:16)
    at FBXLoader.load (file:///C:/WWW/lib/webaverse_app_github_gonnavis_r134/node_modules/three/examples/jsm/loaders/FBXLoader.js:87:10)
    at o (file:///C:/WWW/lib/webaverse_app_github_gonnavis_r134/animations-baker.mjs:211:21)
    at new Promise (<anonymous>)
    at file:///C:/WWW/lib/webaverse_app_github_gonnavis_r134/animations-baker.mjs:210:17
    at baker (file:///C:/WWW/lib/webaverse_app_github_gonnavis_r134/animations-baker.mjs:219:7)
    at file:///C:/WWW/lib/webaverse_app_github_gonnavis_r134/animations-baker.mjs:309:11
    at file:///C:/WWW/lib/webaverse_app_github_gonnavis_r134/animations-baker.mjs:313:3
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
```

So, may we need use an old `webaverse/app` folder at our local which dedicated to run `node ./animations-baker.mjs`.

**Comment by avaer** [comment]
Thanks for the investigation!

It seems the only reason we need `animations-baker.mjs` to be `.mjs` is because of this import:

https://github.com/webaverse/app/blob/aef2d05b9d9d92fbab6518363066a6a7f349a10b/animations-baker.mjs#L7

If we solve that import (which we want to share between frontend and backend), then we could rename to `.js` and avoid this whole headache.

**Comment by avaer** [comment]
This is blocking issue https://github.com/webaverse/app/issues/2194

**Comment by avaer** [comment]
Fixed!
