### ISSUE TITLE
Bot: tokencollab command error

### ISSUE THREAD

**Issue by avaer** [webaverse/app#992]
```
Error: invalid address (argument="address", value="QmbMpESd6H6KNexVYYZbS4CqHQwdkhbVP6bPXydYdWWCjb", code=INVALID_ARGUMENT, version=address/5.0.10) (argument="a", value="QmbMpESd6H6KNexVYYZbS4CqHQwdkhbVP6bPXydYdWWCjb", code=INVALID_ARGUMENT, version=abi/5.0.7)
at Logger.makeError (/home/ubuntu/ethereum-bot/node_modules/@ethersproject/logger/lib/index.js:179:21)
    at Logger.throwError (/home/ubuntu/ethereum-bot/node_modules/@ethersproject/logger/lib/index.js:188:20)
    at Logger.throwArgumentError (/home/ubuntu/ethereum-bot/node_modules/@ethersproject/logger/lib/index.js:191:21)
    at AddressCoder.Coder._throwError (/home/ubuntu/ethereum-bot/node_modules/@ethersproject/abi/lib/coders/abstract-coder.js:40:16)
    at AddressCoder.encode (/home/ubuntu/ethereum-bot/node_modules/@ethersproject/abi/lib/coders/address.js:29:18)
    at /home/ubuntu/ethereum-bot/node_modules/@ethersproject/abi/lib/coders/array.js:71:19
    at Array.forEach (<anonymous>)
    at Object.pack (/home/ubuntu/ethereum-bot/node_modules/@ethersproject/abi/lib/coders/array.js:57:12)
    at TupleCoder.encode (/home/ubuntu/ethereum-bot/node_modules/@ethersproject/abi/lib/coders/tuple.js:36:24)
    at AbiCoder.encode (/home/ubuntu/ethereum-bot/node_modules/@ethersproject/abi/lib/abi-coder.js:86:15)
    at ABICoder.encodeParameters (/home/ubuntu/ethereum-bot/node_modules/web3-eth-abi/lib/index.js:121:27)
    at /home/ubuntu/ethereum-bot/node_modules/web3-eth-contract/lib/index.js:439:20
    at Array.map (<anonymous>)
    at Object._encodeMethodABI (/home/ubuntu/ethereum-bot/node_modules/web3-eth-contract/lib/index.js:438:8)
    at fn (/home/ubuntu/ethereum-bot/index.js:141:31)
    at Client.<anonymous> (/home/ubuntu/ethereum-bot/discordbot.js:1491:91)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by avaer** [comment]
Should be fixed now.
